[project]
name = "bdqn-word"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-docx>=1.1.2",
    "pywin32>=310",
    "tkzs-bd-ads-db-tool>=0.2.2",
    "tqdm>=4.67.1",
]
