import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://cas.baidu.com/?tpl=www2&fromu=https%3A%2F%2Fwww2.baidu.com%2Fcommon%2Fappinit.ajax")
    page.get_by_role("textbox", name="请输入账号").click()
    page.get_by_role("textbox", name="请输入账号").fill("BDCC-金蛛账号中心")
    page.get_by_role("textbox", name="请输入密码").click()
    page.get_by_role("textbox", name="请输入密码").fill("JinZhu2025#")
    page.get_by_role("button", name="登录").click()
    with page.expect_popup() as page1_info:
        page.get_by_text("金蛛-BCNT").click()
    page1 = page1_info.value
    with page1.expect_popup() as page2_info:
        page1.locator("div").filter(has_text=re.compile(r"^巧舱$")).nth(4).click()
    page2 = page2_info.value
    page2.get_by_text("金蛛-BCNT下滑查看").click()
    page2.locator("body").press("F5")
    page2.goto("https://aiagent.baidu.com/mbot/user/64261946/index?relationSource=mbotRole&ucUserId=64261946")
    page2.get_by_text("金蛛-BCNT下滑查看").click()
    page2.get_by_text("金蛛-BCNT下滑查看").click()
    page2.get_by_text("金蛛-BCNT下滑查看").click()
    page2.goto("https://aiagent.baidu.com/mbot/user/64261946/creatorChat?relationSource=mbotIndex&ucUserId=64261946")
    page2.get_by_role("textbox", name="请输入智能体名称").click()
    page2.get_by_role("textbox", name="请输入智能体名称").click()
    page2.get_by_role("textbox", name="请输入智能体名称").fill("深圳北大青鸟")
    page2.locator("div").filter(has_text=re.compile(r"^设置头像$")).first.click()
    page2.get_by_role("textbox", name="请输入智能体名称").click()
    page2.get_by_role("textbox", name="请输入智能体名称").dblclick()
    page2.get_by_role("textbox", name="请输入智能体名称").press("ControlOrMeta+a")
    page2.get_by_role("textbox", name="请输入智能体名称").fill("深圳北大青鸟教师助理")
    page2.locator("div").filter(has_text=re.compile(r"^设置头像$")).first.click()
    page2.locator(".vi > div > div > .vi").click()
    page2.locator(".cc-album").first.click()
    page2.get_by_role("button", name="​ 确定").click()
    page2.get_by_text("下一步").click()
    page2.get_by_role("textbox", name="本公司是一家专门做xx的公司，主要经营产品有A、B、C等。").click()
    page2.get_by_role("textbox", name="本公司是一家专门做xx的公司，主要经营产品有A、B、C等。").fill("专注IT培训教育26年，培养100W学员从事IT互联网行业。学AI，好工作，就找金蛛。 金蛛始终践行“职业教育就是就业教育”的教育本质， 坚持帮助学员成功就业，永远是硬道理，始终保持回归职业教育的本真，即坚守“教学为本，师爱为魂”的教育理念， 以及“内育职业素养，外塑专业技能”的青鸟校训，主要业务有软件开发培训，网络工程培训，AI开发培训，Java培训，大数据培训，Python培训，电商培训，新媒体培训，UI培训等。")
    page2.locator("div").filter(has_text=re.compile(r"^391/600$")).first.click()
    page2.get_by_role("textbox", name="目标用户是有xx需求的网民。").click()
    page2.get_by_role("textbox", name="目标用户是有xx需求的网民。").fill("目标用户是希望通过学一门技术获得好发展的人群。")
    page2.get_by_role("textbox", name="本公司是一家专门做xx的公司，主要经营产品有A、B、C等。").click()
    page2.get_by_role("textbox", name="本公司是一家专门做xx的公司，主要经营产品有A、B、C等。").press("ArrowUp")
    page2.get_by_role("textbox", name="本公司是一家专门做xx的公司，主要经营产品有A、B、C等。").press("ArrowUp")
    page2.get_by_role("textbox", name="本公司是一家专门做xx的公司，主要经营产品有A、B、C等。").press("ArrowRight")
    page2.get_by_role("textbox", name="本公司是一家专门做xx的公司，主要经营产品有A、B、C等。").press("ArrowRight")
    page2.get_by_role("textbox", name="本公司是一家专门做xx的公司，主要经营产品有A、B、C等。").press("ArrowRight")
    page2.get_by_role("textbox", name="本公司是一家专门做xx的公司，主要经营产品有A、B、C等。").press("ArrowRight")
    page2.get_by_role("textbox", name="本公司是一家专门做xx的公司，主要经营产品有A、B、C等。").press("ArrowRight")
    page2.get_by_role("textbox", name="本公司是一家专门做xx的公司，主要经营产品有A、B、C等。").press("ArrowRight")
    page2.get_by_role("textbox", name="本公司是一家专门做xx的公司，主要经营产品有A、B、C等。").press("ArrowRight")
    page2.get_by_role("textbox", name="本公司是一家专门做xx的公司，主要经营产品有A、B、C等。").press("ArrowRight")
    page2.get_by_role("textbox", name="本公司是一家专门做xx的公司，主要经营产品有A、B、C等。").press("ArrowRight")
    page2.get_by_role("textbox", name="本公司是一家专门做xx的公司，主要经营产品有A、B、C等。").press("ArrowRight")
    page2.get_by_role("textbox", name="本公司是一家专门做xx的公司，主要经营产品有A、B、C等。").press("ArrowRight")
    page2.get_by_role("textbox", name="本公司是一家专门做xx的公司，主要经营产品有A、B、C等。").press("ArrowRight")
    page2.get_by_role("textbox", name="本公司是一家专门做xx的公司，主要经营产品有A、B、C等。").press("ArrowRight")
    page2.get_by_role("textbox", name="本公司是一家专门做xx的公司，主要经营产品有A、B、C等。").press("ArrowRight")
    page2.get_by_role("textbox", name="本公司是一家专门做xx的公司，主要经营产品有A、B、C等。").press("ArrowLeft")
    page2.get_by_role("textbox", name="本公司是一家专门做xx的公司，主要经营产品有A、B、C等。").fill("专注IT培训教育26年，培养100W学员从事IT互联网行业。学AI，好工作，就找北大青鸟。 金蛛始终践行“职业教育就是就业教育”的教育本质， 坚持帮助学员成功就业，永远是硬道理，始终保持回归职业教育的本真，即坚守“教学为本，师爱为魂”的教育理念， 以及“内育职业素养，外塑专业技能”的青鸟校训，主要业务有软件开发培训，网络工程培训，AI开发培训，Java培训，大数据培训，Python培训，电商培训，新媒体培训，UI培训等。")
    page2.get_by_role("textbox", name="本公司是一家专门做xx的公司，主要经营产品有A、B、C等。").press("ArrowRight")
    page2.get_by_role("textbox", name="本公司是一家专门做xx的公司，主要经营产品有A、B、C等。").press("ArrowRight")
    page2.get_by_role("textbox", name="本公司是一家专门做xx的公司，主要经营产品有A、B、C等。").press("ArrowRight")
    page2.get_by_role("textbox", name="本公司是一家专门做xx的公司，主要经营产品有A、B、C等。").press("ArrowRight")
    page2.get_by_role("textbox", name="本公司是一家专门做xx的公司，主要经营产品有A、B、C等。").fill("专注IT培训教育26年，培养100W学员从事IT互联网行业。学AI，好工作，就找北大青鸟。 北大青鸟始终践行“职业教育就是就业教育”的教育本质， 坚持帮助学员成功就业，永远是硬道理，始终保持回归职业教育的本真，即坚守“教学为本，师爱为魂”的教育理念， 以及“内育职业素养，外塑专业技能”的青鸟校训，主要业务有软件开发培训，网络工程培训，AI开发培训，Java培训，大数据培训，Python培训，电商培训，新媒体培训，UI培训等。")
    page2.get_by_text("下一步").click()
    page2.get_by_text("创建智能体").click()
    page2.locator("#app span").nth(2).click()
    page2.locator("span").filter(has_text="我已阅读并同意").first.click()
    page2.locator("span").filter(has_text="我已阅读并同意").first.click()
    page2.get_by_text("创建智能体").click()
    page2.get_by_text("用于智能体理解商家的优势及特色。用户询问有转化意向的问题时，通过凸显服务优势提升转化动力").click()
    page2.get_by_text("暂未填写").click()
    page2.get_by_role("textbox", name="xx公司是xx地区最大的xx设备生产商，累积服务国内外xx").click()
    page2.get_by_role("textbox", name="xx公司是xx地区最大的xx设备生产商，累积服务国内外xx").click()
    page2.get_by_role("textbox", name="xx公司是xx地区最大的xx设备生产商，累积服务国内外xx").fill("全国60多个城市200余家分校，800+所合作学校，20000+家合作用人企业。")
    page2.get_by_role("textbox", name="荣获“xx奖”、“xx企业”，全线产品均已通过国际CE").click()
    page2.get_by_role("textbox", name="荣获“xx奖”、“xx企业”，全线产品均已通过国际CE").fill("教材被纳入国家“十三五”和“十四五”规划高校教学用书")
    page2.get_by_role("textbox", name="公司xx年来专注于xx、xx等领域。").click()
    page2.get_by_role("textbox", name="公司xx年来专注于xx、xx等领域。").fill("26年培养了100万+IT互联网技术人才，与华/阿等企业深度合作，参与大数据等岗位行业标准制定。")
    page2.get_by_role("textbox", name="拥有N+研发人员，X").click()
    page2.get_by_role("textbox", name="拥有N+研发人员，X").fill("拥有200余人的研发团队，覆盖教育学、软件开发、网络安全等多个领域，课程每10-18个月更新一次，确保技术前沿性。")
    page2.get_by_role("textbox", name="有集xx、xx").click()
    page2.get_by_role("textbox", name="有集xx、xx").fill("配备青鸟AI实验室、NovaAI开放平台等先进教学设施，提供真实企业项目实训环境。")
    page2.get_by_role("textbox", name="我公司免费xx，终身售后，提供全年7*24").click()
    page2.get_by_role("textbox", name="我公司免费xx，终身售后，提供全年7*24").fill("入学签订协议，提供全程就业跟踪服务，​技能学历双认证。")
    page2.get_by_role("textbox", name="采买超过x台设备的客户可享受大客户N折优惠。").click()
    page2.get_by_role("textbox", name="采买超过x台设备的客户可享受大客户N折优惠。").fill("完善奖助学金政策，提供先学后付，特殊群体专项补贴或学费减免。")
    page2.get_by_role("button", name="​ 确认").click()
    page2.locator("div").filter(has_text=re.compile(r"^广泛合作网络$")).get_by_role("button").click()
    page2.locator("div").filter(has_text=re.compile(r"^教材权威规划$")).click()
    page2.locator("div").filter(has_text=re.compile(r"^教材权威规划$")).get_by_role("button").click()
    page2.locator("div").filter(has_text=re.compile(r"^技术人才培养$")).get_by_role("button").click()
    page2.locator("div").filter(has_text=re.compile(r"^课程前沿更新$")).click()
    page2.locator("div").filter(has_text=re.compile(r"^课程前沿更新$")).get_by_role("button").click()
    page2.locator("div").filter(has_text=re.compile(r"^真实项目实训$")).click()
    page2.get_by_role("button", name="​", exact=True).click()
    page2.locator("#roleSetting-baseInfoserviceTag div").nth(2).click()
    page2.locator("#roleSetting-baseInfoserviceTag").get_by_role("textbox").fill("权威教材")
    page2.locator("#roleSetting-baseInfoserviceTag").get_by_role("textbox").press("Enter")
    page2.locator("#roleSetting-baseInfoserviceTag").get_by_text("添加").click()
    page2.locator("#roleSetting-baseInfoserviceTag").get_by_role("textbox").fill("26年教学沉淀")
    page2.locator("#roleSetting-baseInfoserviceTag").get_by_role("textbox").press("Enter")
    page2.locator("#roleSetting-baseInfoserviceTag").get_by_text("添加").click()
    page2.locator("#roleSetting-baseInfoserviceTag").get_by_role("textbox").fill("100")
    page2.locator("#roleSetting-baseInfoserviceTag").get_by_role("textbox").press("CapsLock")
    page2.locator("#roleSetting-baseInfoserviceTag").get_by_role("textbox").fill("100W+")
    page2.locator("#roleSetting-baseInfoserviceTag").get_by_role("textbox").press("CapsLock")
    page2.locator("#roleSetting-baseInfoserviceTag").get_by_role("textbox").fill("100W+学员选择")
    page2.locator("#roleSetting-baseInfoserviceTag").get_by_role("textbox").press("Enter")
    page2.locator("#roleSetting-baseInfoserviceTag").get_by_text("添加").click()
    page2.locator("#roleSetting-baseInfoserviceTag").get_by_role("textbox").fill("行业定制标准")
    page2.locator("#roleSetting-baseInfoserviceTag").get_by_role("textbox").press("Enter")
    page2.locator("#roleSetting-baseInfoserviceTag").get_by_text("添加").click()
    page2.locator("#roleSetting-baseInfoserviceTag").get_by_role("textbox").fill("全真项目实战")
    page2.locator("#roleSetting-baseInfoserviceTag").get_by_role("textbox").press("Enter")
    page2.locator("#roleSetting-baseInfoserviceTag").get_by_text("添加").click()
    page2.locator("#roleSetting-baseInfoserviceTag").get_by_role("textbox").press("CapsLock")
    page2.locator("#roleSetting-baseInfoserviceTag").get_by_role("textbox").fill("AI+")
    page2.locator("#roleSetting-baseInfoserviceTag").get_by_role("textbox").press("CapsLock")
    page2.locator("#roleSetting-baseInfoserviceTag").get_by_role("textbox").fill("AI+全新升级")
    page2.locator("#roleSetting-baseInfoserviceTag").get_by_role("textbox").press("Enter")
    page2.get_by_role("paragraph").filter(has_text="Hi").click()
    page2.locator("div").filter(has_text=re.compile(r"^Hi，您好，欢迎向深圳北大青鸟教师助理进行咨询~快速下证、全网可查、价格透明，有什么可以帮您？$")).nth(1).press("ControlOrMeta+a")
    page2.locator("div").filter(has_text=re.compile(r"^角色扩展信息$")).first.click()
    page2.locator("#roleSetting-baseExtInfo").get_by_role("img").nth(1).click()
    page2.get_by_role("textbox", name="请输入商家简称").click()
    page2.get_by_role("textbox", name="请输入商家简称").fill("深圳北大青鸟")
    page2.locator("label").filter(has_text="线下业务").click()
    page2.get_by_role("button", name="​ 批量上传").click()
    page2.get_by_role("button", name="​ 点击选择文件").click()
    page2.get_by_role("button", name="​ 点击选择文件").set_input_files("addressTemplate.xlsx")
    page2.get_by_role("button", name="​ 开始上传").click()
    page2.get_by_role("button", name="​ 确认").click()
    page2.get_by_text("返回").click()
    page2.locator("div").filter(has_text=re.compile(r"^线索收集$")).nth(1).click()
    page2.locator("div").filter(has_text=re.compile(r"^线索获取方式主动索要示例被动回答示例主动发送示例电话方案请选择电话方案优先发送客服电话$")).get_by_label("主动发送").check()
    page2.get_by_text("请选择电话方案").first.click()
    page2.get_by_text("转18806662618").click()
    page2.get_by_role("checkbox", name="优先发送客服电话 ​").check()
    page2.locator("div").filter(has_text=re.compile(r"^线索获取方式主动索要示例被动回答示例主动发送示例微信方案请选择微信方案优先发送客服微信$")).get_by_label("被动回答").check()
    page2.locator("div").filter(has_text=re.compile(r"^线索获取方式主动索要示例被动回答示例主动发送示例微信方案请选择微信方案请选择微信方案优先发送客服微信$")).get_by_label("主动发送").check()
    page2.get_by_text("请选择微信方案").nth(1).click()
    page2.get_by_role("option", name="挂机短信默认方案_2618").click()
    page2.get_by_role("switch").click()
    page2.locator("#clueCollect-clueVerify").get_by_role("img").click()
    page2.get_by_text("号码异常验证").click()
    page2.get_by_text("返回").click()
    page2.locator("div").filter(has_text=re.compile(r"^对话设置$")).nth(2).click()
    page2.locator("div").filter(has_text=re.compile(r"^知识供给$")).nth(2).click()
    page2.locator("div").filter(has_text=re.compile(r"^对话工具$")).nth(2).click()
    with page2.expect_popup() as page3_info:
        page2.locator("div").filter(has_text=re.compile(r"^服务预约提供预约信息收集能力，帮助用户完成预约诉求设置$")).get_by_role("button").click()
    page3 = page3_info.value
    page3.get_by_role("radio", name="预约到校 ​").check()
    page3.get_by_role("button", name="​ 确认").click()
    page3.locator("div").filter(has_text=re.compile(r"^对话数据下发第三方咨询工具未设置$")).locator("span").nth(1).click()
    page3.locator("div").filter(has_text=re.compile(r"^请选择工具类型$")).nth(2).click()
    page3.get_by_role("option", name="全时易聊").click()
    page3.get_by_text("请选择客服账号").click()
    page3.get_by_text("全时易聊36790").click()
    page3.get_by_role("button", name="​ 确认").click()
    page3.get_by_text("请选择一级接待方案").click()
    page3.get_by_text("百度基木鱼接待组").click()
    page3.get_by_role("button", name="​ 确认").click()
    page3.locator("a").filter(has_text="配置").click()
    page3.locator("div").filter(has_text=re.compile(r"^高级装修$")).nth(2).click()
    page3.get_by_role("button", name="​ 使用").nth(2).click()
    page3.locator("div").filter(has_text=re.compile(r"^快捷功能$")).nth(1).click()
    page3.locator("#quickConsult").get_by_role("button", name="​").click()
    page3.get_by_text("预约服务卡").click()
    page3.get_by_text("电话咨询").click()
    page3.get_by_text("添加微信").click()
    page3.locator("div").filter(has_text=re.compile(r"^请选择$")).nth(3).click()
    page3.get_by_text("挂机短信默认方案_2618").click()
    page3.locator("#decoration").get_by_text("商家首页").click()
    page3.get_by_role("button", name="​ 提交").click()
    page3.get_by_text("返回").click()
    page3.locator("#roleSetting-baseExtInfo").get_by_role("img").nth(1).click()
    page3.get_by_text("线下业务").click()
    page3.get_by_role("button", name="​ 提交").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
